spring:
  application:
    name: ${project.artifactId}


dubbo:
  scan:
    base-packages: com.zz.dubbo.service.impl
  application:
    id: provide-a
    name: ${dubbo.application.id}
    qos:
      enable: false
  protocol:
    id: dubbo
    name: dubbo
    threadpool: fixed
    threads: 200
    payload: 52428800
    port: 20980
  registry:
    id: dubbo-test
    address: zookeeper://192.168.137.128:2181
    file: /output/cache/${dubbo.application.id}.cache
    timeout: 5000
    session: 60000
    check: true
  provider:
    id: ${dubbo.application.id}
    group: dubbo-spring
    version: 1.0.0
    timeout: 60000
    loadbalance: consistenthash
    weight: 5
    retries: 2
    actives: 200
    executes: 200
    parameters: {hash.arguments: 0, hash.nodes: 320}
